name = "casper3"
license = "MIT"
licenselink = "https://github.com/funkeyfreak/casper4/blob/master/LICENSE"
description = "The default Casper version 3 theme from Ghost CMS ported over to Hugo"
tags = ["blog", "dark", "light"]
features = ["darkmode"]
min_version = "0.54.0"

[author]
  name = "Dalin Williams"
  homepage = "https://dalinwilliams.com"
  repo = "https://github.com/funkeyfreak/projects/casper4"

[original]
  name = "Ghost"
  homepage = "https://jonathanjanssens.com"
  repo = "https://github.com/jonathanjanssens/projects/hugo-casper3"